voteContractCodePath: "/app/contracts/TomorrowDAO.Contracts.Vote.dll.patched"
governanceContractCodePath: "/app/contracts/TomorrowDAO.Contracts.Governance.dll.patched"
daoContractCodePath: "/app/contracts/TomorrowDAO.Contracts.DAO.dll.patched"
electionContractCodePath: "/app/contracts/TomorrowDAO.Contracts.Election.dll.patched"
treasuryContractCodePath: "/app/contracts/TomorrowDAO.Contracts.Treasury.dll.patched"
timelockContractCodePath: "/app/contracts/TomorrowDAO.Contracts.Timelock.dll.patched"
merkleTreeContractCodePath: "/app/contracts/MerkleTreeWithHistory.dll.patched"
voteContractAddress: NCi6nskU1A3QTNxcxgo1rnrrtkhVh56jXqj4m2T6uXs5hjsSF
daoContractAddress: defdwNRez3U8WpdVE73p6xuiixeYYJ9hn9ZS5GMSpTHbJ2omt
governanceContractAddress: j5c9dv4ird82fbcBiaHvBys4m3qZFaYnxPKUgDpkhc7nsbvaa